config/routes.rb
SociaLoginRails::Application.routes.draw do

  get "home/index"
  resources :tips
  root :to => "tips#index", via: :get

  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  match 'tagged', to: 'tips#index', :as => 'tagged', via: 'get'
  match 'tags/:tag', to: 'tips#index', as:  :tag , via: 'get'
  get "pages/terms"
  get "pages/welcome"
  get "pages/tags"
  match '/tags', to: 'pages#tags', via: 'get'
  match '/conditions', to: 'pages#conditions', via: 'get'
  match '/symptoms', to: 'pages#symptoms', via: 'get'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users do
    post 'follow' => 'following_relationships#create'
    delete 'follow' => 'following_relationships#destroy'
  end
  get :my_tips, to: 'tips#my_tips', as: 'my_tips'
  resource :dashboard, only: [:show]
  resource :search, only: [:show]
  resources :shouts, only: [:show]
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
  resources :hashtags, only: [:show]

resources :tips do
  member { post :vote }
end

  

 

end

app/models/user.rb
class User < ActiveRecord::Base
  # include Concerns::following // ---> couldnt move code to conncerns see l 26
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates_presence_of :email
  mount_uploader :image, ImageUploader
  has_many :authorizations
  
  has_many :tips, dependent: :destroy

  has_many :evaluations , class_name: "RSEvaluation", as: :source

  has_reputation :votes, source: {reputation: :votes, of: :tips}, aggregated_by: :sum

  # reputation system 
  def voted_for?(tip)
    evaluations.where(target_type: tip.class, target_id: tip.id).present?
  end

  # folowing folow followers section
  has_many :shouts
  
  # --- couldn't move to concerns hangs the rails server ?----------------

  has_many :followed_user_relationships,
  foreign_key: :follower_id,
  class_name: 'FollowingRelationship'
  has_many :followed_users, through: :followed_user_relationships

  has_many :follower_relationships, 
  foreign_key: :followed_user_id, 
  class_name: 'FollowingRelationship'
  has_many :follower_relationships, through: :follower_relationships

  def following? user
    followed_user_ids.include? user.id
  end
    def can_follow? user 
    self != user
  end

  def follow user
    followed_users << user
  end

  def unfollow user 
    followed_users.delete(user)
  end



  # -------------??????????? do i need   that?-----------------
  # def self.create_with_omniauth(auth)
  #   create! do |user|
  #     user.provider = auth["provider"]
  #     user.uid = auth["uid"]
  #     user.name = auth["info"]["name"] || ""
  #     user.address = auth["info"]["location"] || ""
  #     user.avatar = auth["info"]["image"] || ""
  #     user.oauth_token = auth["credentials"]["token"] || ""
  #     user.oauth_secret = auth["credentials"]["secret"] || ""
  #   end
  # end






  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end



  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user.nil? ? User.where('email = ?', auth["info"]["email"]).first : current_user
      if user.blank?
       user = User.new
       user.password = Devise.friendly_token[0,10]
       user.name = auth.info.name
       user.email = auth.info.email
       auth.provider == "twitter" ?  user.save(:validate => false) :  user.save
     end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
     authorization.save
   end
   authorization.user
 end

 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]
  

  def index
  @users = User.all.paginate(page: params[:page])
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    @tips = @user.tips
    @shouts = @user.shouts
  end

 

  

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end


  # PATCH/PUT /users/1
  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end


def user_params
  params.require(:user ).permit(:id,:name,:about, :avatar,:email, :password,:password_confirmation)
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

     def validate_authorization_for_user
     redirect_to @user unless @user == current_user
     end




# Before filters

    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  end

app/helpers/users_helper.rb
module UsersHelper

	def follow_button user
		if current_user.following? user 
			button_to 'Unfollow', user_follow_path(user), method: :delete
		else
			button_to 'Follow', user_follow_path(user)
		end
	end
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    
    <%= f.input :name, :required => true, :autofocus => true %>
    <%= f.input :about, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<div>
Connect Account



<% ['facebook', 'twitter'].each do |provider| %>

  <% if current_user.authorizations.pluck(:provider).include?(provider.to_s) %>
    <%= provider.to_s.titleize %> Connected
  <% else %>
      <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider) %>
  <% end %>
<br/>
<% end %>

</div>

app/views/users/_user.html.erb
<div class="panel callout radius">
  
   <%= link_to user.name, user %> tips to date: [ <%= user.tips.count %> ]
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
                                  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile </h1>



<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
     

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>


  </div>
</div>




<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

<!-- <h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
 -->

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel callout radius">
	<p>
		<strong>Name:</strong>
		<ul>

			
			<h2> <%= @user.name %></h2></ul>
				<% if current_user.email != nil %>
				<%= gravatar @user %>		
				<% end %>
			<h5>Tips to date (<%= @user.tips.count %>)</h5>
			<% if user_signed_in? %>
			<% if current_user.can_follow?(@user) %>
			<%= follow_button @user %>
			<% end %>
			<% if current_user == @user %>
			<%= link_to 'Edit', edit_user_path(@user) %>
			<% if @user.tips.any? %>
			<% end %>
			<% end %>
		</div>

		<div >


			<%= render @tips  %>
<%= render @shouts %>
			<% end %>
		</div>

		<!--List Recently Created Events-->


</div>