config/routes.rb
SociaLoginRails::Application.routes.draw do

  get "home/index"
  resources :tips
  root :to => "tips#index", via: :get

  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  match 'tagged', to: 'tips#index', :as => 'tagged', via: 'get'
  match 'tags/:tag', to: 'tips#index', as:  :tag , via: 'get'
  get "pages/terms"
  get "pages/welcome"
  get "pages/tags"
  match '/tags', to: 'pages#tags', via: 'get'
  match '/conditions', to: 'pages#conditions', via: 'get'
  match '/symptoms', to: 'pages#symptoms', via: 'get'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users do
    post 'follow' => 'following_relationships#create'
    delete 'follow' => 'following_relationships#destroy'
  end
  get :my_tips, to: 'tips#my_tips', as: 'my_tips'
  resource :dashboard, only: [:show]
  resource :search, only: [:show]
  resources :shouts, only: [:show]
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
  resources :hashtags, only: [:show]

resources :tips do
  member { post :vote }
end

  

 

end

app/models/tip.rb
# require 'open-uri'
class Tip < ActiveRecord::Base
	DIFFICULTY=%w(Easy Medium Hard)
	belongs_to :condition_name
	belongs_to :symptom_name
	belongs_to :tip_type
	
	acts_as_taggable_on :tags
	validates_presence_of :title, :condition_name_id, :symptom_name_id
	belongs_to :user
	validates :user_id, presence: true
	
	has_reputation :votes, source: :user, aggregated_by: :sum
	

# authority system 






end

app/models/tip_type.rb
class TipType < ActiveRecord::Base
	has_many :tips
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]


  # GET /tips
  # GET /tips.json
  def index

    if params[:sort_by].blank?
    @tips = Tip.tagged_with(params[:tag])
    @tips = Tip.find_with_reputation(:votes, :all, order: "votes desc")
    
    
    
      else
        @tips = Tip.where(params[:sort_by])
      end
    
  end

  # reputation system 
def vote
  value = params[:type] == "up" ? 1 : -1
  @tip = Tip.find(params[:id])
  @tip.add_or_update_evaluation(:votes, value, current_user)
  redirect_to :back, notice: "Thank you for voting"
end



  # ------------------------------------------------

def tag_cloud
    @tags = Tip.tag_counts_on(:tags)
  end


  def my_tips
    @tips = current_user.tips.all? { |e|  }
  end



  # GET /tips/1
  # GET /tips/1.json
  def show
  
      @tips = Tip.find(params[:id])
 
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json


# Call twitter and send an update when tip is created

def create

 client = Twitter::REST::Client.new do |config|
   config.consumer_key= ENV["TWITTER_KEY"]
   config.consumer_secret= ENV["TWITTER_SECRET"]
   config.access_token= ENV["TWITTER_TOKEN"]
   config.access_token_secret = ENV["TWITTER_TOKEN_SECRET"]
 end
# web link adress to be inserted in tweet post aftet tip creation

web_url = Rails.application.routes.url_helpers.tips_url(:host => 'chronicillnesses.co.uk' )
@tip = current_user.tips.new(tip_params)

# posts a tweet to twitter uncomment on production server

# client.update( "I just shared  "  "#{@tip.title} tip @ #{web_url}")


# ------------------------------------------------------------------------------------------
respond_to do |format|
  if @tip.save
    format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
    format.json { render :show, status: :created, location: @tip }
  else
    format.html { render :new }
    format.json { render json: @tip.errors, status: :unprocessable_entity }
  end
end
end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  

  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  

  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




# implements act_as_taggable

def tagged
  if params[:tag].present? 
    @tips = Tip.tagged_with(params[:tag])
  else 
    @tips = Tip.postall
  end  
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:title, :votes, :difficulty_level, :condition_name_id, :symptom_name_id, :tip_type_id, :what_needed, :my_tip, :user_id,:tips_url ,:tag_list, :tag )
    end
  end

app/helpers/tips_helper.rb
module TipsHelper

    include ActsAsTaggableOn::TagsHelper
end

app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
 <div class="form-group">
<%= f.label :Is_it_difficult_? %><br>
<%=f.select :difficulty_level, Tip::DIFFICULTY,{} ,
:class => "form-control"%>
</div>
  <div class="form-group">
    <%= f.label :condition_name_id %><br>
    <%= f.select(:condition_name_id,
   options_from_collection_for_select(ConditionName.all, :id, :name),
  {:prompt =>'Please Choose'}, :class => "form-control") %>
  </div>
   <div class="form-group">
    <%= f.label :symptom_name_id %><br>
    <%= f.select( :symptom_name_id,
  options_from_collection_for_select(SymptomName.all, :id, :name),
  {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>
 
  <div class="field">
    <%= f.label :what_is_needed_? %><br>
    <%= f.text_area :what_needed %>
  </div>
  <div class="field">
    <%= f.label :my_tip %>  [ tip description ] <br>
    <%= f.text_area :my_tip %>
  </div>
  <div class="field">
<%= f.label :tags_comma_separated %>
<%= f.text_field :tag_list %>

</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tips/_tag_cloud.html.erb
<!-- Displaying the tag cloud div-->
<div class="col-lg-4">
<h3>Search Tags</h3>
<div>
	<!-- Generating the tag cloud -->
<% tag_cloud Tip.tag_counts, %w{css1 css2 css3 css4}
do |tag, css_class| %>
<%= link_to tag.name, tag_path(tag.name), class:
css_class %>
<% end %>
</div>
</div>
</div>

app/views/tips/_tip.html.erb
<!-- this is part of profile view listing user Tips -->
<table>

  <thead >

    <tr>
      <th>TIP TITLE  </th>



      <th>Condition name </th>
      <th>Tag</th>
      <th >---------------</th>
    </tr>
  </thead>

     <tbody>
     

      <tr>
        <td ><%= tip.title %>

<div>


  <span class="label"><%= pluralize tip.reputation_for(:votes).to_i, "vote" %> </span>
<% if user_signed_in? %>
  <span class="success label"><%= link_to "up", vote_tip_path(tip, type: "up"), method: "post" %></span>




  <span class="warning label"><%= link_to "down", vote_tip_path(tip, type: "down"), method: "post" %></span>
  <% end %></div>


        </td>
        
        <td><%= tip.condition_name.name %></td>
        <td><%= tip.symptom_name.name %></td>

        <td><% for tag in tip.tags %>
         <%= link_to tag.name, tagged_url(:tag => tag.name) %>
         <% end %></td>
         
         
         
         <td><%= link_to 'Show', tip, class: 'button tiny radius success' %>
          <% if user_signed_in? %>
          <% if tip.user == current_user %>
          <%= link_to 'Edit', edit_tip_path(tip), class: 'button tiny radius success' %>
          <%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny radius alert' %></td>
          



          
          <% end %>

          <% end %>
          
        </tr>
        
        
      </tbody>
   </table>

app/views/tips/edit.html.erb
<h1>Editing tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<h1>Coping Tips List</h1>

<table>

  <thead >

    <div class="panel callout radius"> <h5>Choose a <%= link_to "Tag",   tags_path %> or
      <%= link_to "Condition",   conditions_path %>  or  <%= link_to "Symptom",   symptoms_path %>  to look for Tips</h5>  </div>
      


      <tr>
        <th>TIP TITLE  </th>
        
        <th>Condition name </th>
        <th>Category</th>
        <th>Tag Name</th>
        <th ></th>
      </tr>
    </thead>

    <tbody>
      <% @tips.each do |tip| %>

      <tr>
        <td ><strong><h4><%= tip.title %></h4></strong> <br>

By: <%= tip.user.name   %> <br>
 <div><span class="label"><%= pluralize tip.reputation_for(:votes).to_i, "vote" %> </span>
<% if user_signed_in? %>
  <span class="success label"><%= link_to "up", vote_tip_path(tip, type: "up"), method: "post" %></span>




  <span class="warning label"><%= link_to "down", vote_tip_path(tip, type: "down"), method: "post" %></span>
  <% end %></div>

        </td>
        
        <td><%= tip.condition_name.name %></td>
        <td><%= tip.symptom_name.name %></td>

        <td><% for tag in tip.tags %>
         <%= link_to tag.name, tagged_url(:tag => tag.name) %>
         <% end %></td>
         
         
         
         <td><%= link_to 'Show', tip, class: 'button tiny radius success' %>
          <% if user_signed_in? %>
          <% if tip.user == current_user %>
          <%= link_to 'Edit', edit_tip_path(tip), class: 'button tiny radius success' %>
          <%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny radius alert' %></td>
          



          
          <% end %>

          <% end %>
          
        </tr>
        <% end %>
        
      </tbody>
      <div class="fb-like" data-href="https://www.facebook.com/pages/FibroTrust/482527011777039" data-layout="button_count" data-action="recommend" data-show-faces="false" data-share="true"></div>
    </table>


    <%= link_to 'Share your Tip', new_tip_path, class: 'button  radius success' %>

    <br>

app/views/tips/my_tips.html.erb
<div class="row">
<div class="col-lg-8">
<!--List Recently Created Events-->
<h3>Recently Created Tips</h3>
<% @tips.each do |tip| %>
<h3><%= tip.title %></h3>
<label>Created:</label><%= l tip.created_at,:format => :date_format %>
<label>Organized By:</label><br/>
<%@tip_owner = Tip.tip_owner(tip.user_id)%>
<br/>
<%end%><br/><br/>
<% end %>
</div>
<%= render "tag_cloud"%>
<br>

app/views/tips/new.html.erb
<h1>New tip</h1>

<%= render 'form' %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  
  <div class="panel callout radius"><strong>Tip Title:</strong><h2> <%= @tip.title %></h2></div>
</p>

<div class="panel callout radius">


  <p>
    <strong>Condition name:</strong>
    <%= @tip.condition_name.name %>
  </p>

  <p>
    <strong>Symptom name:</strong>
    <%= @tip.symptom_name.name %>
  </p>

 
</div>
<div class="panel callout radius">
  <p>
    <strong>What needed:</strong>
    <%= @tip.what_needed %>
  </p>
</div>
<div class="panel callout radius">
  <p>
    <strong>My tip:</strong>
    <%= @tip.my_tip %>

  </p>
</div>

  
  <div class="panel callout radius">
    <strong>Tags:</strong>
    <% @tip.tags.any? %>
    <% @tip.tags.each do |tag| %>
    <%= link_to tag.name, tagged_url(:tag => tag.name) %>
    <% end %>

  </div>


      <% if current_user == @user %>
  
  
<%= link_to 'Edit', edit_tip_path(@tip) %> |
    <%= link_to 'Back', tips_path %>
 <% end %>
<div class="panel callout radius">
  <div class='spread'>  <div class='twshare left'>   <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="fibrotr">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>  
  </div>  
  <div class="fb-like" data-href="https://www.facebook.com/pages/FibroTrust/482527011777039" data-layout="button_count" data-action="recommend" data-show-faces="false" data-share="true"></div>