config/routes.rb
SociaLoginRails::Application.routes.draw do

  get "home/index"
  resources :tips
  root :to => "tips#index", via: :get

  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  match 'tagged', to: 'tips#index', :as => 'tagged', via: 'get'
  match 'tags/:tag', to: 'tips#index', as:  :tag , via: 'get'
  get "pages/terms"
  get "pages/welcome"
  get "pages/tags"
  match '/tags', to: 'pages#tags', via: 'get'
  match '/conditions', to: 'pages#conditions', via: 'get'
  match '/symptoms', to: 'pages#symptoms', via: 'get'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users do
    post 'follow' => 'following_relationships#create'
    delete 'follow' => 'following_relationships#destroy'
  end
  get :my_tips, to: 'tips#my_tips', as: 'my_tips'
  resource :dashboard, only: [:show]
  resource :search, only: [:show]
  resources :shouts, only: [:show]
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
  resources :hashtags, only: [:show]

resources :tips do
  member { post :vote }
end

  

 

end

app/views/layouts/_categories.html.erb
<h3 class="text-center">Categories</h3>



<div class="panel callout radius">
  <h6>Conditions</h6>
  <ul class="square">
  <% @condition_names.each do |fp| %>
    <li><%= link_to "#{fp.name}", tips_path(sort_by: { condition_name_id: fp.id }) %></li>
  <% end %>
  </ul>
</div>
<div class="panel callout radius">
  <h6>Symptoms</h6>
  <ul class="square">
  <% @symptom_names.each do |ft| %>
    <li><%= link_to "#{ft.name}", tips_path(sort_by: { symptom_name_id: ft.id }) %></li>
  <% end %>
  </ul>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %> radius">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Chronically Coping', root_path %></li>
   
  </ul>
<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  <div class="top-bar-section">
   <ul class="nav navbar-nav">

          
          <!-- <li class="active"><%= link_to 'Tips List', tips_path %></li> -->
        
        <% if user_signed_in? %>
       
       <li class="active"><%= link_to "Users", users_path %></li>
      
        <li><%= link_to "Profile", current_user %></li>
            <% end %>
            <li class="active"><%= link_to 'Share your Tip', new_tip_path, class: 'button  radius success' %></li>
        
 
        </ul>

    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
<!-- </nav> -->

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
<li>
  <%= form_for(:search, url: search_path, method: :get) do |form| %>
<%= form.text_field :term %></li>
<li><%= form.submit "Search" %>
<% end %></li>

          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Dasboard", dashboard_path %></li>
          
          <li><%= link_to "Logout", destroy_user_session_path %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          
        
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <!-- facebook 'like' head script  -->
  
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=318980918202032&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <!-- site title and description -->

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Chronically Coping" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chronically Coping" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'vendor/modernizr' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div id="fb-root"></div>

<!-- navigation bar -->

  <header>
    <%= render 'layouts/navigation' %>
  </header>

<!-- main content -->

  <div class="row">
    <div class="large-centered-6 columns">
      
      <%= render 'layouts/messages' %>
    </div>
  </div>

<!-- sidebar -->

  <main class="row">
    <div class="large-3 columns">
      <%= render 'layouts/categories' %>
    </div>
    <div class="large-9 columns">
      <%= yield %>
    </div>
  </main>

</body>

</html>